packages:
  - "."

allowBuilds:
  '@parcel/watcher': true
  electron: true
  electron-winstaller: true
  esbuild: true
  vue-demi: true

minimumReleaseAgeExclude:
  - rollup@4.59.0
  - serialize-javascript@7.0.3
  - picomatch@2.3.2
  - picomatch@4.0.4
  - lodash-es@4.17.24
  - lodash@4.17.24
  - defu@6.1.5
  - postcss@8.5.10
  - immutable@5.1.5
  - serialize-javascript@7.0.5
  - lodash-es@4.17.23
  - lodash@4.17.23
  - esbuild@0.28.1
  - form-data@4.0.6

overrides:
  serialize-javascript@<=7.0.2: ^7.0.3
  serialize-javascript@>=5.0.0 <7.0.5: ^7.0.5
