name = "test-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true

[observability]
enabled = true

[[d1_databases]]
binding = "db"
database_name = "test-email"
database_id = "e65f099d-796d-4eaa-8dff-529b368b20db"

[[kv_namespaces]]
binding = "kv"
id = "9be10cd058e04c55b526f8c0c116f50c"

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

[vars]
ai_model = ""
analysis_cache = false
orm_log = false
domain = ["example.com"]
admin = "admin@example.com"
init_secret = "vitest-database-init-secret"
lifecycle_service_secret = "vitest-lifecycle-service-secret"
jwt_secret = "b7f29a1d-18e2-4d3b-941f-f6b2c97c02fd"
