mail_location = maildir:/var/vmail/chemvault.science/%n/Maildir
mail_privileged_group = mail

namespace inbox {
  inbox = yes
  separator = .

  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }

  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }

  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }

  mailbox Archive {
    auto = subscribe
    special_use = \Archive
  }
}
